/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GenresRouteImport } from './routes/genres'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GenreGenreIdRouteImport } from './routes/genre.$genreId'
import { Route as AnimeMalIdRouteImport } from './routes/anime.$malId'
import { Route as AuthenticatedWatchlistRouteImport } from './routes/_authenticated.watchlist'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated.history'
import { Route as AuthenticatedConsoleRouteImport } from './routes/_authenticated.console'
import { Route as WatchMalIdEpisodeRouteImport } from './routes/watch.$malId.$episode'
import { Route as ApiPublicSyncAnikotoRouteImport } from './routes/api/public/sync-anikoto'
import { Route as ApiPublicScoutRouteImport } from './routes/api/public/scout'
import { Route as ApiPublicHealthCheckRouteImport } from './routes/api/public/health-check'
import { Route as ApiPublicWorkerRpcRouteImport } from './routes/api/public/worker.rpc'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresRoute = GenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenreGenreIdRoute = GenreGenreIdRouteImport.update({
  id: '/genre/$genreId',
  path: '/genre/$genreId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeMalIdRoute = AnimeMalIdRouteImport.update({
  id: '/anime/$malId',
  path: '/anime/$malId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWatchlistRoute = AuthenticatedWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConsoleRoute = AuthenticatedConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const WatchMalIdEpisodeRoute = WatchMalIdEpisodeRouteImport.update({
  id: '/watch/$malId/$episode',
  path: '/watch/$malId/$episode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncAnikotoRoute = ApiPublicSyncAnikotoRouteImport.update({
  id: '/api/public/sync-anikoto',
  path: '/api/public/sync-anikoto',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScoutRoute = ApiPublicScoutRouteImport.update({
  id: '/api/public/scout',
  path: '/api/public/scout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthCheckRoute = ApiPublicHealthCheckRouteImport.update({
  id: '/api/public/health-check',
  path: '/api/public/health-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerRpcRoute = ApiPublicWorkerRpcRouteImport.update({
  id: '/api/public/worker/rpc',
  path: '/api/public/worker/rpc',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/dmca': typeof DmcaRoute
  '/genres': typeof GenresRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/anime/$malId': typeof AnimeMalIdRoute
  '/genre/$genreId': typeof GenreGenreIdRoute
  '/api/public/health-check': typeof ApiPublicHealthCheckRoute
  '/api/public/scout': typeof ApiPublicScoutRoute
  '/api/public/sync-anikoto': typeof ApiPublicSyncAnikotoRoute
  '/watch/$malId/$episode': typeof WatchMalIdEpisodeRoute
  '/api/public/worker/rpc': typeof ApiPublicWorkerRpcRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/dmca': typeof DmcaRoute
  '/genres': typeof GenresRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/anime/$malId': typeof AnimeMalIdRoute
  '/genre/$genreId': typeof GenreGenreIdRoute
  '/api/public/health-check': typeof ApiPublicHealthCheckRoute
  '/api/public/scout': typeof ApiPublicScoutRoute
  '/api/public/sync-anikoto': typeof ApiPublicSyncAnikotoRoute
  '/watch/$malId/$episode': typeof WatchMalIdEpisodeRoute
  '/api/public/worker/rpc': typeof ApiPublicWorkerRpcRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/dmca': typeof DmcaRoute
  '/genres': typeof GenresRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/_authenticated/console': typeof AuthenticatedConsoleRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/watchlist': typeof AuthenticatedWatchlistRoute
  '/anime/$malId': typeof AnimeMalIdRoute
  '/genre/$genreId': typeof GenreGenreIdRoute
  '/api/public/health-check': typeof ApiPublicHealthCheckRoute
  '/api/public/scout': typeof ApiPublicScoutRoute
  '/api/public/sync-anikoto': typeof ApiPublicSyncAnikotoRoute
  '/watch/$malId/$episode': typeof WatchMalIdEpisodeRoute
  '/api/public/worker/rpc': typeof ApiPublicWorkerRpcRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/browse'
    | '/dmca'
    | '/genres'
    | '/login'
    | '/privacy'
    | '/schedule'
    | '/search'
    | '/terms'
    | '/console'
    | '/history'
    | '/profile'
    | '/watchlist'
    | '/anime/$malId'
    | '/genre/$genreId'
    | '/api/public/health-check'
    | '/api/public/scout'
    | '/api/public/sync-anikoto'
    | '/watch/$malId/$episode'
    | '/api/public/worker/rpc'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/browse'
    | '/dmca'
    | '/genres'
    | '/login'
    | '/privacy'
    | '/schedule'
    | '/search'
    | '/terms'
    | '/console'
    | '/history'
    | '/profile'
    | '/watchlist'
    | '/anime/$malId'
    | '/genre/$genreId'
    | '/api/public/health-check'
    | '/api/public/scout'
    | '/api/public/sync-anikoto'
    | '/watch/$malId/$episode'
    | '/api/public/worker/rpc'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/browse'
    | '/dmca'
    | '/genres'
    | '/login'
    | '/privacy'
    | '/schedule'
    | '/search'
    | '/terms'
    | '/_authenticated/console'
    | '/_authenticated/history'
    | '/_authenticated/profile'
    | '/_authenticated/watchlist'
    | '/anime/$malId'
    | '/genre/$genreId'
    | '/api/public/health-check'
    | '/api/public/scout'
    | '/api/public/sync-anikoto'
    | '/watch/$malId/$episode'
    | '/api/public/worker/rpc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  BrowseRoute: typeof BrowseRoute
  DmcaRoute: typeof DmcaRoute
  GenresRoute: typeof GenresRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ScheduleRoute: typeof ScheduleRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  AnimeMalIdRoute: typeof AnimeMalIdRoute
  GenreGenreIdRoute: typeof GenreGenreIdRoute
  ApiPublicHealthCheckRoute: typeof ApiPublicHealthCheckRoute
  ApiPublicScoutRoute: typeof ApiPublicScoutRoute
  ApiPublicSyncAnikotoRoute: typeof ApiPublicSyncAnikotoRoute
  WatchMalIdEpisodeRoute: typeof WatchMalIdEpisodeRoute
  ApiPublicWorkerRpcRoute: typeof ApiPublicWorkerRpcRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres': {
      id: '/genres'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof GenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genre/$genreId': {
      id: '/genre/$genreId'
      path: '/genre/$genreId'
      fullPath: '/genre/$genreId'
      preLoaderRoute: typeof GenreGenreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$malId': {
      id: '/anime/$malId'
      path: '/anime/$malId'
      fullPath: '/anime/$malId'
      preLoaderRoute: typeof AnimeMalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/watchlist': {
      id: '/_authenticated/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedWatchlistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/console': {
      id: '/_authenticated/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthenticatedConsoleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/watch/$malId/$episode': {
      id: '/watch/$malId/$episode'
      path: '/watch/$malId/$episode'
      fullPath: '/watch/$malId/$episode'
      preLoaderRoute: typeof WatchMalIdEpisodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-anikoto': {
      id: '/api/public/sync-anikoto'
      path: '/api/public/sync-anikoto'
      fullPath: '/api/public/sync-anikoto'
      preLoaderRoute: typeof ApiPublicSyncAnikotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scout': {
      id: '/api/public/scout'
      path: '/api/public/scout'
      fullPath: '/api/public/scout'
      preLoaderRoute: typeof ApiPublicScoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health-check': {
      id: '/api/public/health-check'
      path: '/api/public/health-check'
      fullPath: '/api/public/health-check'
      preLoaderRoute: typeof ApiPublicHealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/rpc': {
      id: '/api/public/worker/rpc'
      path: '/api/public/worker/rpc'
      fullPath: '/api/public/worker/rpc'
      preLoaderRoute: typeof ApiPublicWorkerRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedConsoleRoute: typeof AuthenticatedConsoleRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedWatchlistRoute: typeof AuthenticatedWatchlistRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConsoleRoute: AuthenticatedConsoleRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedWatchlistRoute: AuthenticatedWatchlistRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  BrowseRoute: BrowseRoute,
  DmcaRoute: DmcaRoute,
  GenresRoute: GenresRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ScheduleRoute: ScheduleRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  AnimeMalIdRoute: AnimeMalIdRoute,
  GenreGenreIdRoute: GenreGenreIdRoute,
  ApiPublicHealthCheckRoute: ApiPublicHealthCheckRoute,
  ApiPublicScoutRoute: ApiPublicScoutRoute,
  ApiPublicSyncAnikotoRoute: ApiPublicSyncAnikotoRoute,
  WatchMalIdEpisodeRoute: WatchMalIdEpisodeRoute,
  ApiPublicWorkerRpcRoute: ApiPublicWorkerRpcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
